version: '3.1'

services:

  notitas_pg_db:
    image: postgres:15.2
    container_name: notitas_pg_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: notitas
      TZ: America/Hermosillo
    volumes:
      - ./DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    environment:
      TZ: America/Hermosillo
      ADMINER_DESIGN: "ng9"
    ports:
      - 8080:8080
    depends_on:
      notitas_pg_db:
        condition: service_started